### ISSUE TITLE
Data in CSV were incomplete.

### ISSUE THREAD

**Issue by aaronli7** [ITI/PyMU#2]
Hi, when I used the 'pmuToCSV.py' example to save the stream data from my PMU device to the CSV file. 
- I found the data was **incomplete**, the rate sample rate of the PMU device should be 60 per second while in the CSV file the number of the data sample is unstable between 40 to 50 per second.
- In addition, the number of measurements or the channel name is also incomplete, only phasor angles, freq, and rocof. I expect the magnitude value were included.

I walked through your code but still can't figure it out. Do you have some comments or suggestions? I'd appreciate it.

<img width="587" alt="snaptshot_pmuoutput" src="https://user-images.githubusercontent.com/64019008/107128232-20343500-688a-11eb-90d3-10eec782c608.png">

**Comment by cdrew3** [comment]
Hello!  Happy to offer some suggestions for these 2 issues...

- Originally the goal was 30 frames/sec and during testing it was consistently getting around 40 frames/sec so there was no need to make it faster (for my use at least).  Currently there is nothing limiting it except system resources and efficiency of the code (most likely the latter).  
  - The main bottleneck I can think of is the write to disk.  Write now it's 1 write per data frame which isn't efficient.  This would mean rewriting the file IO portion of the example.  Here's a couple ideas of where to start. 
    - Build up buffer of frames and write all the data at once instead of a write for each data frame
    - Look into StringIO or cStringIO.  I've not used either, a quick search brought these to my attention as possible solutions.

- The lack of measurement output can be fixed by modifying the example code.  On [line 25](https://github.com/ITI/PyMU/blob/master/examples/pmuToCsv.py#L25) you'll see where the angles, freq, and ROCOF are processed by looping through each phasor.  All of that data is buried in pmuDataFrame.py with magnitude data specifically stored in the [Phasor class](https://github.com/ITI/PyMU/blob/master/pymu/pmuDataFrame.py#L161).  All of these attributes are accessible and can be added to the CSV file, just be sure to add the appropriate headers in the [createCsvFile function](https://github.com/ITI/PyMU/blob/master/examples/pmuToCsv.py#L55).

Hopefully these suggestions help, happy to answer any other questions you may have.

**Comment by aaronli7** [comment]
Thanks for your reply!
With your suggestion, by adding couples of lines I successfully get the magnitude of the phasor and print the corresponding header information.

But for the data buffer, I still can't figure out how to solve this issue. For the StringIO, do you mean to save the data to this StringIo object then flush it to the disk periodically?
And my goal is to save the streaming data into the InfluxDB database on an AWS server.

**Comment by cdrew3** [comment]
Sweet, glad the magnitude part worked!

You have the right idea with storing to a buffer then flushing it to disk.  I haven't used StringIO before, a Google search brought it up as a way to increase performance.  It might be as simple as still using the existing write command, but only do it once a second or at some other interval.  If that still doesn't work then yeah, looking at the StringIO documentation could probably give you an idea of how to make writes faster.

**Comment by aaronli7** [comment]
Hi. Thanks for your reply.
But even I uncomment the line [writing csv file ](https://github.com/ITI/PyMU/blob/6bc6ee546d2df27b570f3d6974eb18655f1a447d/examples/pmuToCsv.py#L122). The value of [p](https://github.com/ITI/PyMU/blob/6bc6ee546d2df27b570f3d6974eb18655f1a447d/examples/pmuToCsv.py#L144) still is around 40 per second.

**Comment by cdrew3** [comment]
What happens if you commet out [this line](https://github.com/ITI/PyMU/blob/6bc6ee546d2df27b570f3d6974eb18655f1a447d/examples/pmuToCsv.py#L121)?  I'm wondering if the processing of the bytes into the DataFrame class are slowing it down.

**Comment by aaronli-uga** [comment]
If I comment out (this line)[https://github.com/ITI/PyMU/blob/6bc6ee546d2df27b570f3d6974eb18655f1a447d/examples/pmuToCsv.py#L121]. It becomes even slower... around 30 points per second.

**Comment by aaronli7** [comment]
If I comment out [This line](https://github.com/ITI/PyMU/blob/6bc6ee546d2df27b570f3d6974eb18655f1a447d/examples/pmuToCsv.py#L121) It becomes even slower... around 30 points per second.

**Comment by cdrew3** [comment]
That's very odd since that line is what converts all the bytes to a class and it should be faster.  Are you running in TCP or UDP mode?  UDP should be faster but I don't know your whole setup so I'm not sure if it's possible.

**Comment by aaronli7** [comment]
Yeah, it is odd. 
The PMU device is running in TCP mode. I can switch to UDP to see if it works.

**Comment by aaronli7** [comment]
Hi. I think I found the issue.
I discovered using Wireshark that multiple PMU data frames are sometimes combined into one TCP/IP packet. The current python code appears to assume one data frame per TCP/IP packet, and therefore the extra data frames are getting dropped because the code doesn't parse beyond the first data frame.

**Comment by cdrew3** [comment]
From what I remember, each data frame starts with a header (4 bytes), which includes the length of remaining bytes in the frame.  In TCP mode the client will read the first 4 bytes to get the full length of the frame to read, then read that number of bytes.  There was never any testing with data frames combined so it kind of makes sense you're seeing weird behavior.  PyMU always expects the 4 byte header and a single frame (data, config, or command) to follow.  

I know the standard describes concentrators but this was never written to work with those.  Are you using a concentrator?

**Comment by aaronli7** [comment]
No, we are not using a concentrator.

**Comment by cdrew3** [comment]
For the combined data frames, is there a header between each one?

**Comment by aaronli7** [comment]
Yes, there is a header between them. Each one starts with SYNC and FRAMESIZE
<img width="956" alt="df1" src="https://user-images.githubusercontent.com/64019008/107434999-9094bd80-6af9-11eb-9c00-e063989449bc.png">

**Comment by cdrew3** [comment]
Yeah I don't think PyMU can handle multiple frames being sent at once.  If you look [here](https://github.com/ITI/PyMU/blob/6bc6ee546d2df27b570f3d6974eb18655f1a447d/pymu/tools.py#L83) you'll see that PyMU only reads the number of bytes specified in the FRAMESIZE.  If more than 1 frame is being delivered (which I'm not sure how that's possible since PyMU, as the client, is requesting a specific number of bytes, no more) then it makes sense that PyMU misses it.  I may just not know enough about TCP to understand how multiple frames are being sent at once despite PyMU only asking for 1.

**Comment by aaronli7** [comment]
Thank you so much for the quick response!
Could you point to the code where it asks for one data frame per TCP packet?

**Comment by cdrew3** [comment]
[This function](https://github.com/ITI/PyMU/blob/6bc6ee546d2df27b570f3d6974eb18655f1a447d/pymu/tools.py#L70) is where it asks for a single data frame.  It reads the 4 bytes of HEADER and FRAMESIZE then requests FRAMESIZE number of bytes.

**Comment by cdrew3** [comment]
And [here is the code with the socket module](https://github.com/ITI/PyMU/blob/6bc6ee546d2df27b570f3d6974eb18655f1a447d/pymu/client.py#L64) underneath the getDataSample function.

**Comment by cdrew3** [comment]
If it helps, the client/server code included isn't necessary for PyMU to work.  It was useful for our specific application but it's certainly not a robust solution relative to either something you write yourself or a Python module that someone else wrote.  As long as you grab the bytes of the frame and input them into the right classes you can still parse the data.

**Comment by aaronli7** [comment]
Thanks so much for your suggestions. I will keep looking into it.

**Comment by aaronli7** [comment]
Hi!
We think we found a potential error in the code. In [this line of code](https://github.com/ITI/PyMU/blob/6bc6ee546d2df27b570f3d6974eb18655f1a447d/pymu/tools.py#L82)
We found this if statement always goes to the "else" and never to the "if" even we are the "client".

**Comment by cdrew3** [comment]
That is a very good catch!  I don't have a test setup for this code any more so it would take a while to get one back up and running.  A quick look tells me the code should be using 'isinstance(rcvr, Client)' instead.  Would you be comfortable seeing if that works and testing it out?  If so you could submit a PR and we'd happily approve it.  If not, it would be this weekend at the earliest that I could try to get my test environment setup and going to test it out.

**Comment by aaronli7** [comment]
Hi, it works. by changing it to **isinstance(rcvr, Client)** as you suggested. 
I will submit a PR later this day.

**Comment by cdrew3** [comment]
Awesome!  Any change in performance?

**Comment by aaronli7** [comment]
I guess it should have improvement in performance. But in my case, I hasn't solve the multi-dataframe issue yet so I can't tell right now. But I will let you know.
Besides, the PR has been submitted. Thanks!

**Comment by iadnan1990** [comment]
Hello aaronli-uga have you found any solution for receiving multi-dataframes?
